"""Rasterising the pages a golden set names.

The bake off needs an image of every page in a golden set, at the dpi under
test, and it needs those images to be the ones the fleet would have sent. So
this builds the same command the Go side builds, `pdftoppm -png -r <dpi> -gray
-f N -l N <pdf> <prefix>`, and writes to the same place under the same name,
`images/<book>/0042.png`, four digits, no exceptions.

It exists at all because `bourbaki render` refuses to rasterise a born digital
volume unless the page is one the native extraction could not read. That guard
is right for the corpus, where rendering a page whose text layer is perfect is
work for nothing. It is wrong for a bake off, where a page with a perfect text
layer is the most valuable page there is: it is the one with an answer already
written down.

Nothing here is committed. Images stay in the corpus checkout, which does not
track them, for the reason the corpus README gives: a page is a couple of
hundred kilobytes and the Markdown is what replaces it.
"""

from __future__ import annotations

import re
import struct
import subprocess
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from local_ocr import corpus as corpuslib

DEFAULT_DPI = 300

_PNG = b"\x89PNG\r\n\x1a\n"
# 0.0254 metres to the inch, and pHYs counts pixels per metre.
_PER_METRE = 0.0254

# `- id: alg-viii` and `  pdf: pdf/en/....pdf`, which is all this needs out of
# manifests/books.yaml. A YAML parser would be one dependency to read two keys,
# and the file is generated by `bourbaki books add` rather than written by hand,
# so its shape is a program's shape and not a person's.
_ID = re.compile(r"^\s*-\s+id:\s*(\S+)\s*$")
_PDF = re.compile(r"^\s+pdf:\s*(.+?)\s*$")


class NoSource(Exception):
    """The volume has no PDF recorded, or the PDF is not on this machine."""


def sources(corpus: Path) -> dict[str, Path]:
    """Every volume's PDF, by book id."""
    manifest = corpus / "manifests" / "books.yaml"
    out: dict[str, Path] = {}
    book = ""
    for line in manifest.read_text(encoding="utf-8").split("\n"):
        found = _ID.match(line)
        if found:
            book = found.group(1)
            continue
        found = _PDF.match(line)
        if found and book:
            out[book] = corpus / found.group(1)
            book = ""
    return out


def image_path(corpus: Path, book: str, page: int) -> Path:
    """Where the fleet expects this page's image, and therefore where it goes."""
    return corpus / "images" / book / f"{page:04d}.png"


def dpi_of(path: Path) -> int | None:
    """What an image on disk was rendered at, or None if it does not say.

    pdftoppm writes a pHYs chunk, which is the resolution in pixels per metre,
    so a page carries its own dpi and a set does not have to be trusted to be
    uniform. This matters: the corpus already held two `lie-vii-ix` pages at
    600 dpi from a fleet retry, sitting in a directory of 300 dpi pages, and a
    bake off that read them would have scored two models on one page and the
    rest on another.

    Only the header is read, so this costs nothing on 200 pages.
    """
    with path.open("rb") as handle:
        head = handle.read(8)
        if head != _PNG:
            return None
        while True:
            field_ = handle.read(8)
            if len(field_) < 8:
                return None
            length, kind = struct.unpack(">I", field_[:4])[0], field_[4:]
            if kind == b"pHYs":
                x, _y, unit = struct.unpack(">IIB", handle.read(9))
                return round(x * _PER_METRE) if unit == 1 else None
            if kind == b"IDAT":
                return None
            handle.seek(length + 4, 1)


@dataclass
class Renderer:
    """One page at a time, which is slower and is what a scattered set needs.

    `bourbaki render` batches 25 pages a call because it renders whole volumes.
    A golden set is 200 pages scattered over six of them, 41 pages out of the
    580 of `ts-iii-v-fr`, so the spans are almost all one page long and batching
    buys nothing.
    """

    corpus: Path
    dpi: int = DEFAULT_DPI
    gray: bool = True
    """As the Go side does. It is not the saving it looks like: poppler 26 still
    writes an RGB PNG, 464 kB against 464 kB on a measured page, so this is here
    to match the fleet's pages rather than to make them smaller."""
    run: object = field(default=None, repr=False)
    """Anything with a `run(command)`. None means actually run pdftoppm."""

    def command(self, source: Path, page: int, prefix: Path) -> list[str]:
        args = ["pdftoppm", "-png", "-r", str(self.dpi)]
        if self.gray:
            args.append("-gray")
        args += ["-f", str(page), "-l", str(page), str(source), str(prefix)]
        return args

    def _run(self, command: Sequence[str]) -> None:
        if self.run is not None:
            self.run.run(list(command))  # type: ignore[attr-defined]
            return
        subprocess.run(list(command), check=True, capture_output=True)

    def render(self, book: str, page: int, source: Path) -> Path:
        """Rasterise one page and put it where the fleet would look for it.

        pdftoppm names its output `<prefix>-N.png` with N padded to the width of
        the volume's page count, so the width depends on the book and cannot be
        predicted from here. The file is found rather than named, and renamed.
        """
        out = image_path(self.corpus, book, page)
        out.parent.mkdir(parents=True, exist_ok=True)
        prefix = out.parent / f".render-{page:04d}"
        self._run(self.command(source, page, prefix))
        written = sorted(out.parent.glob(f"{prefix.name}-*.png"))
        if len(written) != 1:
            for stray in written:
                stray.unlink()
            raise NoSource(f"pdftoppm wrote {len(written)} images for {book}/{page:04d}")
        written[0].replace(out)
        return out


@dataclass
class Built:
    """What a run of `build` did, for a caller that has to report it."""

    made: list[str] = field(default_factory=list)
    had: list[str] = field(default_factory=list)
    failed: list[tuple[str, str]] = field(default_factory=list)
    redone: list[str] = field(default_factory=list)
    """Pages that were on disk at some other dpi, and are in `made` as well."""

    @property
    def total(self) -> int:
        return len(self.made) + len(self.had) + len(self.failed)


def build(
    ids: Sequence[str],
    corpus: Path,
    dpi: int = DEFAULT_DPI,
    overwrite: bool = False,
    renderer: Renderer | None = None,
) -> Built:
    """Rasterise every page id given, skipping the ones already at this dpi.

    A page already on disk at the dpi asked for is left alone, and a page on
    disk at some other dpi is rendered again and listed in `redone`. An image
    with no dpi recorded is treated as the wrong dpi, because the only images
    here are ones this or the fleet wrote and both record it.
    """
    where = sources(corpus)
    render = renderer or Renderer(corpus=corpus, dpi=dpi)
    out = Built()
    for page_id in ids:
        book, _, number = page_id.partition("/")
        page = int(number)
        there = image_path(corpus, book, page)
        if there.exists() and not overwrite:
            if dpi_of(there) == dpi:
                out.had.append(page_id)
                continue
            out.redone.append(page_id)
        source = where.get(book)
        if source is None or not source.exists():
            out.failed.append((page_id, f"no pdf for {book}"))
            continue
        try:
            render.render(book, page, source)
        except (NoSource, subprocess.CalledProcessError) as err:
            out.failed.append((page_id, str(err)))
            continue
        out.made.append(page_id)
    return out


def read_ids(name: str) -> list[str]:
    """The page ids of a golden set, without loading a page of it."""
    from local_ocr import golden

    return list(golden.read_manifest(name))


def corpus_root(path: Path | None = None) -> Path:
    return corpuslib.root(path)
